<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общий вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data.head(3)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0

In [5]:
data.corr().style.background_gradient('Oranges')

**Вывод:** Пропусков в данных нет. Признаки имеют довольно низкую корреляцию между собой.
* Признаки: пол, возраст и зарплата застрахованного, количество членов его семьи.
* Целевой признак: количество страховых выплат клиенту за последние 5 лет.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Изменится ли качество линейной регрессии, при умножении признаков на обратимую матрицу?**

**Ответ:** Нет, не изменится.

**Обоснование:** 


Введем матрицу $А = XP.$ По условию, матрица $P$ обратимая, следовательно из критерия существования обратимости, матрица $P$ должна быть квадратной и ее определитель не равен нулю. Пусть матрица $X$ имеет размерность $(mxn)$, тогда матрица $P$ должна иметь размерность $(nxn)$.

При доказательстве воспользуемся формулами матричного умножения:

$
А_{nxm}^T = P_{nxn}^T  X_{nxm}^T \qquad\qquad(1)
$

$
 (AB)^{-1}= B^{-1}A^{-1} \qquad\qquad\ (2)
$

$
 ABC= (AB)C =A(BC) \qquad(3)
$

$
 A A^{-1}= E \qquad\qquad\qquad\quad(4)
$

$
 EA= A =AE \qquad\qquad\quad\;(5)
$

Подставим матрицу А в формулу обучения:

$$
w = (A^T A)^{-1} A^T y = ((XP)^T XP)^{-1} (XP)^T y 
$$

По формуле (1) раскроем скобки и получим:

$$
w =  (P^T X^T XP)^{-1} P^T X^T y 
$$

Воспользовавшись формулами (2) и (3):

$$
w = (P^T ((X^T X)P))^{-1} P^T X^T y = ((X^T X)P)^{-1} (P^T)^{-1} P^T X^T y = P^{-1}(X^T X)^{-1} (P^T)^{-1} P^T X^T y 
$$

Так как при умножении матрицы на ее обратную получается единичная матрица, а умножение матрицы на единичную не меняет ее значения (по формулам (4) и (5)), выражение примет следующий вид:

$$
w =  P^{-1} (X^T X)^{-1} X^T y
$$

Подставим полученное выражение в формулу предсказаний.

$$
a = Aw = XPw = XPP^{-1} (X^T X)^{-1} X^T y = X(X^T X)^{-1} X^T y
$$

**Ч.Т.Д.** (что требовалось доказать). 
Умножение матрицы $X$ на обратимую матрицу $P$ не повлияет на формулу предсказаний.

  
Есть ещё один способ доказательства   когда мы берём
    
    
$$
w = \arg\min_w MSE(Xw, y)
$$
    
  
и     
    
$$
w_P = \arg\min_w MSE(XPw_p, y)
$$  
    
    
И делая  замену    w_p, видим что задача  
    
$$
\arg\min_w MSE(XPw_p, y)
$$
    
сводится к     
  
    
$$
\arg\min_w MSE(Xw, y)
$$    


Осталось только догадаться какую замену мы делаем.  Можешь попробовать решить и таким способом  

  
</div>
    

    




## Алгоритм преобразования

**Алгоритм**

Введем матрицу зашифрованных признаков $А_{mxn} = X_{mxn}P_{nxn}.$ Так как размерность матрицы признаков 5000x4, а матрица $P$ - квадратная, то ее размерность будет 4х4.

В качестве матрицы $P_{4x4}$ возьмем матрицу случайных чисел и проверим ее на обратимость. Далее обучим модели линейной регрессии на зашифрованных и незашифрованных признаках и определим для каждой из них метрику R2. Полученные результаты сравним.

**Обоснование**

In [6]:
features = data.drop('Страховые выплаты',axis=1)
target = data['Страховые выплаты']

In [7]:
p_matrix = np.random.normal(1,3,size=(4,4))
print(p_matrix)

[[ 0.53052216 -1.71789161 -0.30743901  6.73599387]
 [ 0.53647661  7.94927402 -0.19304034  3.50752611]
 [-1.23081959  2.62428438 -2.69638698 -0.51868442]
 [-6.84541507  0.63501647  3.38752846  0.95373709]]


In [8]:
#Проверим матрицу на обратимость
np.linalg.inv(p_matrix)

array([[-0.02264783,  0.05338782, -0.14823195, -0.11700197],
       [-0.05848075,  0.1117972 ,  0.00324454,  0.00364592],
       [-0.07197853,  0.0790678 , -0.29981807,  0.0545261 ],
       [ 0.13204029,  0.02791579, -0.00118196,  0.01263346]])

Полученная матрица обратима.

In [9]:
#Зашифрованные признаки
ecrypted_features = pd.DataFrame(np.dot(features.values,p_matrix),index=features.index,columns=features.columns)
ecrypted_features.head()

Пол        Возраст       Зарплата   Члены семьи
0 -61032.971217  130489.342577 -133745.628806 -25575.249067
1 -46753.312065  100089.108038 -102468.197593 -19547.708127
2 -25831.653653   55340.500914  -56629.724764 -10790.654621
3 -51327.601893  109600.863408 -112436.615885 -21553.574906
4 -32108.839537   68714.684083  -70381.412764 -13432.716709

In [10]:
#Отедлим тренировочную и тествую выборки для незашифрованных признаков
features_train, features_test, target_train,target_test = train_test_split(features,target,test_size=0.25,
                                                                            random_state=12345)

#Отедлим тренировочную и тествую выборки для зашифрованных признаков
ecrypted_features_train,  ecrypted_features_test, ecrypted_target_train,ecrypted_target_test = train_test_split(
                                                ecrypted_features, target,test_size=0.25,random_state=12345)

## Проверка алгоритма

In [11]:
def linear_model_r2(features_x,target_x):
    model = LinearRegression()
    model.fit(features_x,target_x)
    predictions = model.predict(features_x)
    print(f'Метрика R2: {r2_score(target_x,predictions):.4f}')

In [12]:
#Метрика R2 для незашифрованных признаков
linear_model_r2(features,target)

Метрика R2: 0.4249


In [13]:
#Метрика R2 для зашифрованных признаков
linear_model_r2(ecrypted_features,target)

Метрика R2: 0.4249


In [14]:
def linear_model_r2(features_x,target_x,features_t,target_t):
    model = LinearRegression()
    model.fit(features_x,target_x)
    predictions = model.predict(features_x)
    print(f'Метрика R2 на тренировочной выборке: {r2_score(target_x,predictions):.4f}')
    predictions_t = model.predict(features_t)
    print(f'Метрика R2 на тестовой выборке: {r2_score(target_t,predictions_t):.4f}')

In [15]:
#Метрика R2 для незашифрованных признаков
linear_model_r2(features_train, target_train, features_test, target_test)

Метрика R2 на тренировочной выборке: 0.4214
Метрика R2 на тестовой выборке: 0.4352


In [16]:
#Метрика R2 для зашифрованных признаков
linear_model_r2(ecrypted_features_train, ecrypted_target_train, ecrypted_features_test, ecrypted_target_test)

Метрика R2 на тренировочной выборке: 0.4214
Метрика R2 на тестовой выборке: 0.4352


**Вывод:** Метрики для незашифрованных и зашифрованных признаков не отличаются.

## Общий вывод

* Рассмотрены данные страховой компании. Целевым признаком является количество страховых выплат клиенту за последние 5 лет. 
* Пропуски в данных не обнаружены, проверена корреляция признаков между собой.

* Доказано и обосновано, что качество линейной регрессии, при умножении признаков на обратимую матрицу, не изменится.

* Составлен алгоритм шифрования данных клиентов страховой компании.

* Проведена проверка алгоритма на тестовой и тренировочной выборках.

* Полученные метрики R2 для зашифрованных и незашифрованных данных не отличаются.
